[package]
name = "hermes-diff"
version = "1.0.1"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0"
hbc = { package = "hbc-decomp", git = "https://github.com/SymbioticSec/hermes-decomp", rev = "83115881e576182ea2dab59218d94146a5186f09" }
hermes_rs = { version = "0.1.14", features = ["v76", "v84", "v89", "v90", "v93", "v94", "v95", "v96"] }
rusqlite = "0.31"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
